FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/mediclicks-hub/firestore/indexes?create_composite=Ck5wcm9qZWN0cy9tZWRpY2xpY2tzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvY2xpZW50cy9pbmRleGVzL18QARoKCgZwYWdhZG8QARoNCgljcmVhdGVkQXQQAhoMCghfX25hbWVfXxAC QUIERO QUE ME ELIMINES LA CUESTION DE LOS FILTROS POR AHORA. NO ME INTERESA TENERLO. SIEMPRE HA TIRADOE ESTE ERROR.