FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/mediclicks-hub/firestore/indexes?create_composite=Ckxwcm9qZWN0cy9tZWRpY2xpY2tzLWh1Yi9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaCwoHZHVlRGF0ZRABGgoKBnN0YXR1cxABGgwKCF9fbmFtZV9fEAE . The query contains range and inequality filters on multiple fields, please refer to the documentation for index selection best practices: https://cloud.google.com/firestore/docs/query-data/multiple-range-fields.